services:
  - type: web
    name: java-migration-accelerator-backend
    env: docker
    dockerfilePath: ./Dockerfile.backend
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITLAB_TOKEN
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SONARQUBE_TOKEN
        sync: false
      - key: PORT
        value: "8001"
